services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: washingtonsilver  #${POSTGRES_PASSWORD}
      POSTGRES_USER: "ildimas"              #${POSTGRES_USER}
      POSTGRES_DB: "main_db"                #${POSTGRES_DB}
      DATABASEHOST: "localhost:5432"
    ports:
      - "5432:5432"
  db_test:
    image: postgres
    container_name: db_test
    restart: always
    environment:
      POSTGRES_PASSWORD: washingtonsilver  #${POSTGRES_PASSWORD}
      POSTGRES_USER: "test"                 #${POSTGRES_USER}
      POSTGRES_DB: "main_test_db"                #${POSTGRES_DB}
      DATABASEHOST: "localhost:5433"
    ports:
      - "5433:5432"