"""auto migrations

Revision ID: 122c76a45bc0
Revises: 4458a6c29189
Create Date: 2024-06-23 05:50:26.967341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '122c76a45bc0'
down_revision: Union[str, None] = '4458a6c29189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_files', sa.Column('time_period', sa.Date(), nullable=False))
    op.add_column('prediction_files', sa.Column('building', sa.String(), nullable=False))
    op.add_column('prediction_files', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('prediction_files', sa.Column('main_ledger_id', sa.String(), nullable=True))
    op.add_column('prediction_files', sa.Column('fixed_assets_id', sa.String(), nullable=True))
    op.add_column('prediction_files', sa.Column('fixed_assets_class', sa.String(), nullable=True))
    op.drop_column('prediction_files', 'csv_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_files', sa.Column('csv_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('prediction_files', 'fixed_assets_class')
    op.drop_column('prediction_files', 'fixed_assets_id')
    op.drop_column('prediction_files', 'main_ledger_id')
    op.drop_column('prediction_files', 'price')
    op.drop_column('prediction_files', 'building')
    op.drop_column('prediction_files', 'time_period')
    # ### end Alembic commands ###
