"""auto migrations

Revision ID: 4a8c5e1f9fb5
Revises: 65310cdbd8cd
Create Date: 2024-06-15 01:27:34.338199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8c5e1f9fb5'
down_revision: Union[str, None] = '65310cdbd8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
