"""auto migrations

Revision ID: 69af0ce2c261
Revises: 9bd8d5538180
Create Date: 2024-06-13 17:56:39.147593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69af0ce2c261'
down_revision: Union[str, None] = '9bd8d5538180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('prediction_files',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=True),
    sa.Column('csv_data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.alloc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('allocations', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'allocations', 'categories', ['category_id'], ['category_id'])
    op.create_foreign_key(None, 'allocations', 'users', ['user_uuid'], ['user_id'])
    op.drop_column('allocations', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.drop_column('allocations', 'category_id')
    op.drop_table('prediction_files')
    op.drop_table('categories')
    # ### end Alembic commands ###
