"""auto migrations

Revision ID: 7d8cacfad4c0
Revises: 122c76a45bc0
Create Date: 2024-06-23 11:55:45.940506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8cacfad4c0'
down_revision: Union[str, None] = '122c76a45bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_files', sa.Column('alloc_id', sa.UUID(), nullable=False))
    op.drop_constraint('prediction_files_allocation_id_fkey', 'prediction_files', type_='foreignkey')
    op.create_foreign_key(None, 'prediction_files', 'allocations', ['alloc_id'], ['alloc_id'], ondelete='CASCADE')
    op.drop_column('prediction_files', 'allocation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_files', sa.Column('allocation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prediction_files', type_='foreignkey')
    op.create_foreign_key('prediction_files_allocation_id_fkey', 'prediction_files', 'allocations', ['allocation_id'], ['alloc_id'], ondelete='CASCADE')
    op.drop_column('prediction_files', 'alloc_id')
    # ### end Alembic commands ###
