"""auto migrations

Revision ID: 8cdfecd93c96
Revises: ea4432409fd9
Create Date: 2024-06-14 23:11:50.482440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cdfecd93c96'
down_revision: Union[str, None] = 'ea4432409fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_books', sa.Column('contracts', sa.LargeBinary(), nullable=True))
    op.add_column('reference_books', sa.Column('codes', sa.LargeBinary(), nullable=True))
    op.add_column('reference_books', sa.Column('fixedassets', sa.LargeBinary(), nullable=True))
    op.add_column('reference_books', sa.Column('building_squares', sa.LargeBinary(), nullable=True))
    op.add_column('reference_books', sa.Column('contracts_to_building', sa.LargeBinary(), nullable=True))
    op.drop_column('reference_books', 'bin_codes')
    op.drop_column('reference_books', 'bin_contracts')
    op.drop_column('reference_books', 'bin_building_squares')
    op.drop_column('reference_books', 'bin_fixedassets')
    op.drop_column('reference_books', 'bin_contracts_to_building')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_books', sa.Column('bin_contracts_to_building', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('reference_books', sa.Column('bin_fixedassets', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('reference_books', sa.Column('bin_building_squares', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('reference_books', sa.Column('bin_contracts', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('reference_books', sa.Column('bin_codes', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('reference_books', 'contracts_to_building')
    op.drop_column('reference_books', 'building_squares')
    op.drop_column('reference_books', 'fixedassets')
    op.drop_column('reference_books', 'codes')
    op.drop_column('reference_books', 'contracts')
    # ### end Alembic commands ###
