"""auto migrations

Revision ID: 9bd8d5538180
Revises: da406e6f4f04
Create Date: 2024-06-13 16:40:41.769583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd8d5538180'
down_revision: Union[str, None] = 'da406e6f4f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('alloc_id', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('alloc_result_csv', sa.LargeBinary(), nullable=True),
    sa.Column('alloc_result_xlsx', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('alloc_id')
    )
    op.create_table('bills_to_pay',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=True),
    sa.Column('bills_to_pay', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.alloc_id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('reference_books',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=True),
    sa.Column('reference1', sa.LargeBinary(), nullable=True),
    sa.Column('reference2', sa.LargeBinary(), nullable=True),
    sa.Column('reference3', sa.LargeBinary(), nullable=True),
    sa.Column('reference4', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.alloc_id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('reference_books')
    op.drop_table('bills_to_pay')
    op.drop_table('allocations')
    # ### end Alembic commands ###
