"""auto migrations

Revision ID: a7f96891da2d
Revises: 8cdfecd93c96
Create Date: 2024-06-15 01:21:52.160139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7f96891da2d'
down_revision: Union[str, None] = '8cdfecd93c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills_to_pay', 'bills_to_pay',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills_to_pay', 'bills_to_pay',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
