"""auto migrations

Revision ID: e64a2170b3e1
Revises: 24c5de07c7f3
Create Date: 2024-06-14 01:21:37.634247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64a2170b3e1'
down_revision: Union[str, None] = '24c5de07c7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    # ### end Alembic commands ###
