"""auto migrations

Revision ID: f4cdcf763f82
Revises: 6c2c4e8f45b6
Create Date: 2024-06-14 01:37:04.320152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cdcf763f82'
down_revision: Union[str, None] = '6c2c4e8f45b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint('allocations_user_uuid_fkey', 'allocations', type_='foreignkey')
    op.create_foreign_key(None, 'allocations', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('allocations', 'user_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'allocations', type_='foreignkey')
    op.create_foreign_key('allocations_user_uuid_fkey', 'allocations', 'users', ['user_uuid'], ['user_id'], ondelete='CASCADE')
    op.drop_column('allocations', 'user_id')
    # ### end Alembic commands ###
